version: '1'
services:
  web:
    build:
      context: /app
    ports:
     - "8080:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: "redis:latest"
    volumes:
      - redis_data:/data
volumes:  
  redis_data:
